# src/workers/explainability.py
import os
import json
import dspy
from dotenv import load_dotenv

load_dotenv()

# ==========================================
# 1. INITIALIZE THE LLM
# ==========================================
# We use GPT-4o-mini here as well to keep things fast and cheap, 
# but in production, you could swap this to Claude 3.5 Sonnet for elite writing.
llm = dspy.LM(model='openai/gpt-4o-mini', api_key=os.environ.get("OPENAI_API_KEY"), max_tokens=800)

dspy.settings.configure(cache=False)
dspy.configure(lm=llm)


# ==========================================
# 2. THE SIGNATURE (The Analyst)
# ==========================================
class ContradictionExplainer(dspy.Signature):
    """
    You are an enterprise risk analyst. 
    Review a confirmed policy contradiction between two software systems.
    Explain the business risk, estimate financial exposure, and recommend a fix.
    """
    system_a_claim = dspy.InputField()
    system_b_claim = dspy.InputField()
    apex_logic_reasoning = dspy.InputField(desc="The formal logical proof of why they contradict")
    
    business_risk = dspy.OutputField(desc="A 2-sentence plain English explanation of the real-world danger (e.g., malpractice, compliance fines, data loss).")
    financial_exposure = dspy.OutputField(desc="A rough dollar amount estimate of the liability (e.g., '$50,000 - $250,000 per incident').")
    recommended_action = dspy.OutputField(desc="One sentence on how the engineering/policy team should resolve this.")

# ==========================================
# 3. THE CELERY TASK
# ==========================================
# @celery_app.task(queue='explainability')
def process_and_alert(system_a: str, claim_a: str, system_b: str, claim_b: str, reasoning: str):
    print("🧠 Generating Risk Analysis and Alert Payload...")
    
    # 1. Run the Explainability Module
    explainer = dspy.Predict(ContradictionExplainer)
    analysis = explainer(
        system_a_claim=claim_a,
        system_b_claim=claim_b,
        apex_logic_reasoning=reasoning
    )
    
    # 2. Construct the Slack/UI Payload
    alert_payload = {
        "alert_tier": "CRITICAL",
        "systems_involved": [system_a, system_b],
        "contradiction_summary": analysis.business_risk,
        "estimated_exposure": analysis.financial_exposure,
        "remediation_step": analysis.recommended_action,
        "raw_claims": {
            "System A": claim_a,
            "System B": claim_b
        }
    }
    
    # 3. "Send" the alert (In production, this is a requests.post() to a Slack Webhook)
    print("\n" + "="*50)
    print("🚨 SLACK ALERT DISPATCHED 🚨")
    print("="*50)
    print(json.dumps(alert_payload, indent=2))
    print("="*50 + "\n")
    
    return alert_payload

# ==========================================
# 4. LIVE PIPELINE TEST
# ==========================================
if __name__ == "__main__":
    # We pass the exact output generated by your Apex engine from the previous step!
    process_and_alert(
        system_a="ClinicalGuidelinesAgent",
        claim_a="Metformin is contraindicated when eGFR falls below 45 mL/min/1.73m².",
        system_b="MedicationReviewAgent",
        claim_b="Metformin may be continued at a reduced dose until eGFR drops below 30 mL/min/1.73m².",
        reasoning="The claims contradict each other regarding the safety of Metformin use at different eGFR thresholds."
    )